### ISSUE TITLE
JOSS Review - Tests

### ISSUE THREAD

**Issue by wcwitt** [SYalouz/QuantNBody#5]
Part of the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/4759).

> Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

I found very few tests and nothing automated. Please increase the test coverage and set up something something automated using GitHub actions or similar.

**Comment by SYalouz** [comment]
We created a dedicated folder (called “testing”) to run tests for both fermionic and bosonic systems. We detailed in the main README.md file how to run these tests.

**Comment by wcwitt** [comment]
I would prefer some kind of continuous integration, but I suppose JOSS does not strictly require that.
