### ISSUE TITLE
Not issue but question

### ISSUE THREAD

**Issue by sangkookchoi** [SYalouz/QuantNBody#7]
Hi, Thank you for sharing this wonderful package. I have a question regarding the creation and annihilation operators. Is it possible to use the creation or annihilation operator, instead of the a_dagger_a operator, in this package? I am working with a system in a grand canonical ensemble and there are instances where I need to use either the creation or annihilation operator. Does this package support such cases?

**Comment by SYalouz** [comment]
Thank you very much for your message and kind words.

I'm currently working on a code extension to make this possible. The new functions will be stored under the name "fermionic_fockspace". I hope to have a beta version available in the next week or two. Stay tuned for this release.

Have a nice day!

**Comment by sangkookchoi** [comment]
That will be wonderful. I’ll wait for your update.
Have a good day:)
